qos                : "batch"
walltime           : "12:00"
job                : "job_name"
num_nodes          : 1
num_cpus_for_server: 2
num_cpus_for_client: 4
num_gpus_for_client: 2
trainer            : 'train.fsdp.py'
yaml_config        : 'base.yaml'
ipc_workers        : 2
OMP_NUM_THREADS    : 1
transformers_cache : $HOME/.cache/huggingface
