checkpoint:
  state_dict_type: full
  chkpt_saving_iterations: 100
  preempt_metadata_path: preemptive
  preempt_chkpt_saving_iterations: 100
  directory: experiments/chkpts
  prefix: dummy-0.1
  path_chkpt_prev: null
  pretrain: null
dataset:
  batch_size: 256
  cache_size: 0
  debug: false
  drop_last_in_loader: true
  drop_last_in_sampler: true
  num_workers: 1
  path_train: experiments/datasets/safetensor_dataset.train.csv
  path_eval: experiments/datasets/safetensor_dataset.validate.csv
  pin_memory: true
  prefetch_factor: 2
  seg_size: 2560
  ## seg_size: 100
  num_channels: 1
  input:
    C: 1
    H: 1920
    W: 1920
    total_size: 256000
    ## total_size: 100
  transforms:
    H_pad: 1920
    Hv: 256
    W_pad: 1920
    Wv: 256
    angle_max: 360
    frac_shift_max: 0.1
    num_crop: 8
    num_patch: 100
    sampling_fraction: null
    set:
      uses_instance_norm: false
      batch_sampler: false
      pad: true
      polar_center_crop: false
      random_patch: false
      random_rotate: false
      random_shift: false
    sigma: 0.333
    size_patch: 20
    var_size_patch: 0.2
dist:
  cpu_only: false
  backend: nccl
  uses_unique_world_seed: true
  dtype: bfloat16
  sharding_stage: zero3_hybrid
logging:
  directory: experiments/logs
  prefix: dummy-5.0
  level: info
loss:
  grad_accum_steps: 1
lr_scheduler:
  min_lr: 1.0e-07
  total_iterations: 1000000
  warmup_iterations: 10
  scheduler_update_iterations: 1
misc:
  max_epochs: 5
  max_eval_iter: 10
  max_eval_retry: 2
  compiles_model: true
  data_dump_on: false
  peak_flops_per_sec: 312000000000000
  monitors_dynamics: false
model:
  hf_config:
    hidden_size: 1280
    num_hidden_layers: 32
    num_attention_heads: 16
    intermediate_size: 5120
    hidden_act: gelu
    hidden_dropout_prob: 0.0
    attention_probs_dropout_prob: 0.0
    initializer_range: 0.02
    layer_norm_eps: 1.0e-12
    image_size: 1920
    patch_size: 128
    num_channels: 1
    qkv_bias: true
    decoder_num_attention_heads: 16
    decoder_hidden_size: 512
    decoder_num_hidden_layers: 16
    decoder_intermediate_size: 2048
    mask_ratio: 0.75
    norm_pix_loss: true
  from_scratch: false
optim:
  grad_clip: 1.0
  lr: 0.0003
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.95
  fused: false
